### ISSUE TITLE
[iOS][Edit Goal] "Save" button is enabled when both goal and reason are edited

### ISSUE THREAD

**Issue by nylput** [davidlamys/onepercent.win#32]
**Environment:**
Device & OS: iPhone 6S+ iOS 12.1.4
App Version:  new revision #53

**Steps to Repro:**
1. Tap the goal
2. Tap Edit Goal
3. Edit only reason why I want to accomplish goal

**Expected Result:**
Save button is enabled and we can update reason

**Actual Result:**
Save button is disabled

**Comment:**
Is this expected?

**Comment by davidlamys** [comment]
@nylput can we close this issue? :)

**Comment by nylput** [comment]
This issue will only be closed once it is not reproducible, thanks.

**Comment by nylput** [comment]
Issue is not reproducible

**Environment:**
Device & OS: iPhone 6S+ iOS 12.1.4
App Version: new revision #55

**Steps to Repro:**
1. Tap the goal
2. Tap Edit Goal
3. Edit only reason why I want to accomplish goal
