### ISSUE TITLE
[iOS][Edit Goal] New saved goal is not shown

### ISSUE THREAD

**Issue by nylput** [davidlamys/onepercent.win#33]
**Environment:**
Device & OS: iPhone 6S+ iOS 12.1.4
App Version:  new revision #53

**Steps to Repro:**
1. Tap the goal > Tap Edit Goal
2. Edit Goal > Save
3. Tap the goal again > Tap Edit Goal
4. Edit Goal > Save

**Expected Result:**
New Goal is displayed

**Actual Result:**
New Goal was displayed for a few seconds then old goal is displayed again.

**Comment by davidlamys** [comment]
@nylput can we close this issue?

**Comment by nylput** [comment]
This issue will be closed if it is not reproducible. thanks.

**Comment by nylput** [comment]
Environment:
Device & OS: iPhone 6S+ iOS 12.1.4
App Version: new revision #55

Steps to Repro:

Tap the goal > Tap Edit Goal
Edit Goal > Save
Tap the goal again > Tap Edit Goal
Edit Goal > Save
