### ISSUE TITLE
[iOS][Goal Date] Date when without note has "green color" instead of "yellow"

### ISSUE THREAD

**Issue by nylput** [davidlamys/onepercent.win#34]
**Environment:**
Device & OS: iPhone 6S+ iOS 12.1.4
App Version:  new revision #53

**Steps to Repro:**
1. Tap the goal
2. Tap Reflect
3. Tap Crushed it
4. On Goal Note Screen > Leave Goal Note blank > Tap Save
5. Tap any date (next or previous)

**Expected Result:**
When goal is accomplished without note, The Line below Date displays "Yellow Color"

**Actual Result:**
When goal is accomplished without note, The Line below Date displays "Green Color"

**Comment:**
Is this expected?

**Comment by davidlamys** [comment]
hmmm I'm inclined to disable the save button until there is a note. this will hopefully lead to more meaningful goals after we continuously use the app. wdyt?

**Comment by davidlamys** [comment]
also inclined to make all goals green once a user has added a note, since we want to shift the focus to reflection and refinement of goals, rather than just attainment of goals

**Comment by nylput** [comment]
That makes more sense and that is a good point for the user to focus on reflection and refinement of goals. Thus, I will close this issue.
